const data = [
  {
    id: 1,
    english: "wind",
    transcription: "[wɪnd]",
    russian: "ветер",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 2,
    english: "first",
    transcription: "[fərst]",
    russian: "первый",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 3,
    english: "field",
    transcription: "[fi:ld]",
    russian: "поле",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 4,
    english: "story",
    transcription: "[ˈstôrē]",
    russian: "история",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 5,
    english: "orange",
    transcription: "[ˈɔːrɪndʒ]",
    russian: "апельсин",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 6,
    english: "apple",
    transcription: "[ˈæpl] ",
    russian: "яблоко",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 7,
    english: "plus",
    transcription: "[plus]",
    russian: "плюс",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 8,
    english: "tree",
    transcription: "[trii]",
    russian: "дерево",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 9,
    english: "hello",
    transcription: "[halou]",
    russian: "привет",
    tags: "",
    tags_json: "[]",
  },
  {
    id: 10,
    english: "sea",
    transcription: "[si:] ",
    russian: "море",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 11,
    english: "gray",
    transcription: "[grei]",
    russian: "серый",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 12,
    english: "love",
    transcription: "[ləv]",
    russian: "любовь",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 13,
    english: "ocean",
    transcription: "[ˈəuʃən] ",
    russian: "океан",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 14,
    english: "joke",
    transcription: "[jouk]",
    russian: "шутка",
    tags: "",
    tags_json: "[]",
  },
  {
    id: 15,
    english: "mountain",
    transcription: " [ˈmauntɪn] ",
    russian: "гора",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 16,
    english: "desert",
    transcription: "[ˈdezərt]",
    russian: "пустыня",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 17,
    english: "river",
    transcription: " [ˈrɪvə] ",
    russian: "река",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 18,
    english: "forest",
    transcription: " [ˈfɔrɪst]",
    russian: "лес",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 19,
    english: "clear",
    transcription: "[klir]",
    russian: "чистый",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 20,
    english: "word",
    transcription: "[word]",
    russian: "слово",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 21,
    english: "developer",
    transcription: "[dɪˈveləpər]",
    russian: "разработчик",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 22,
    english: "cat",
    transcription: "[kæt]",
    russian: "кот",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: 23,
    english: "equipment",
    transcription: "[ɪˈkwɪpmənt]",
    russian: "оборудование",
    tags: "",
    tags_json: '[""]',
  },
];

export default data;